<script setup>
import { computed, onMounted, ref } from 'vue'
import { listAdminMembers, restoreMember, suspendMember } from '@/api/adminMemberApi'
const members = ref([]); const status = ref(''); const keyword = ref(''); const feedback = ref(''); const actionMember = ref(null); const reason = ref(''); const isSubmitting = ref(false)
const filtered = computed(() => members.value)
async function load() { feedback.value = ''; try { const { data } = await listAdminMembers({ status: status.value || undefined, keyword: keyword.value || undefined }); members.value = data } catch (error) { feedback.value = error.response?.data?.message || '會員資料載入失敗。' } }
function openSuspend(member) { actionMember.value = member; reason.value = '' }
async function suspend() { if (!reason.value.trim() || !actionMember.value) return; isSubmitting.value = true; try { await suspendMember(actionMember.value.memberId, reason.value.trim()); actionMember.value = null; await load() } catch (error) { feedback.value = error.response?.data?.message || '停權失敗。' } finally { isSubmitting.value = false } }
async function restore(member) { if (!window.confirm(`確定恢復 ${member.email} 的帳號？`)) return; try { await restoreMember(member.memberId); await load() } catch (error) { feedback.value = error.response?.data?.message || '恢復帳號失敗。' } }
onMounted(load)
</script>
<template><section class="admin-members"><header><div><p>平台管理</p><h1>會員管理</h1><span>搜尋會員、停權或恢復帳號。</span></div></header><div class="filters"><input v-model.trim="keyword" placeholder="搜尋姓名、Email 或會員編號" @keyup.enter="load"><select v-model="status" @change="load"><option value="">全部狀態</option><option value="ACTIVE">正常</option><option value="SUSPENDED">已停權</option><option value="DEACTIVATED">已註銷</option></select><button class="dg-btn-primary" @click="load">搜尋</button></div><p v-if="feedback" class="error">{{ feedback }}</p><div class="table"><div class="row head"><b>會員</b><b>角色</b><b>狀態</b><b>註冊時間</b><b>操作</b></div><div v-for="member in filtered" :key="member.memberId" class="row"><span><strong>{{ member.lastName }}{{ member.firstName }}</strong><small>{{ member.email }} · #{{ member.memberId }}</small></span><span>{{ member.roles.join('、') || '—' }}</span><span><em :class="member.status">{{ member.status }}</em></span><span>{{ member.createdAt ? new Date(member.createdAt).toLocaleDateString('zh-TW') : '—' }}</span><span><button v-if="member.status === 'ACTIVE'" class="danger" @click="openSuspend(member)">停權</button><button v-else-if="member.status === 'SUSPENDED'" @click="restore(member)">恢復</button><span v-else>—</span></span></div><p v-if="!members.length && !feedback" class="empty">沒有符合條件的會員。</p></div><div v-if="actionMember" class="modal" role="dialog" aria-modal="true"><form @submit.prevent="suspend"><h2>停權帳號</h2><p>將立即使 {{ actionMember.email }} 的登入憑證失效。</p><label>停權原因<textarea v-model="reason" required maxlength="500" /></label><div><button type="button" @click="actionMember = null">取消</button><button class="danger" :disabled="isSubmitting">確認停權</button></div></form></div></section></template>
<style scoped>.admin-members{display:grid;gap:20px;color:var(--color-text)}header p{margin:0;color:var(--color-primary-active);font-weight:700;font-size:14px}h1{margin:6px 0;font-size:var(--font-size-xl)}header span,small{color:var(--color-text-muted)}.filters{display:flex;gap:10px}.filters input,.filters select,textarea{border:1px solid var(--color-border);border-radius:var(--radius-md);padding:10px;background:var(--color-surface)}.filters input{width:320px}.table{overflow:auto;border:1px solid var(--color-border);border-radius:var(--radius-lg);background:var(--color-surface)}.row{display:grid;grid-template-columns:2fr 1fr 1fr 1fr 100px;gap:12px;align-items:center;min-width:760px;padding:14px 18px;border-bottom:1px solid var(--color-border);font-size:14px}.head{background:var(--color-bg);font-size:13px}.row span:first-child{display:grid;gap:3px}em{width:max-content;padding:4px 8px;border-radius:999px;font-style:normal;font-weight:700}.ACTIVE{background:var(--color-success-soft);color:var(--color-success)}.SUSPENDED,.DEACTIVATED{background:var(--color-danger-soft);color:var(--color-danger)}button{min-height:38px;border:1px solid var(--color-border);border-radius:var(--radius-md);padding:0 12px;background:var(--color-surface);font:inherit}.danger{border-color:var(--color-danger);color:var(--color-danger)}.error{color:var(--color-danger)}.empty{padding:25px;text-align:center;color:var(--color-text-muted)}.modal{position:fixed;inset:0;display:grid;place-items:center;background:#1a1f2e66;padding:20px}.modal form{display:grid;gap:14px;width:min(440px,100%);padding:24px;border-radius:var(--radius-lg);background:var(--color-surface)}.modal h2,.modal p{margin:0}.modal label{display:grid;gap:6px;font-weight:700}.modal textarea{min-height:110px}.modal form>div{display:flex;justify-content:end;gap:10px}@media(max-width:760px){.filters{flex-wrap:wrap}.filters input{width:100%}}</style>
